#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#home:
    #path: /
    #controller: App\Controller\HomeController::index
#bien:
     #path: /proprety
     #controller: App\Controller\PrpretyController::index